"use client";

import { useMemo, useState } from "react";
import { FunnelChart } from "@/components/dashboard/funnel-chart";
import { LeadsFilterLightbox } from "@/components/leads/leads-filter-lightbox";
import { Card } from "@/components/ui/card";
import {
  filterKeyFromFunnelLabel,
  filterLeads,
  type LeadFilterKey,
} from "@/lib/leads/filters";
import { sortLeadsForDisplay } from "@/lib/leads/sort-leads";
import type { FunnelStage, Lead } from "@/lib/types/lead";
import { cn } from "@/lib/utils/cn";

const STAGE_DESCRIPTIONS = [
  "Leads generated by Marketing — webinars, LinkedIn, website forms, events.",
  "Leads showing enough engagement to qualify as interested.",
  "MQLs reviewed and accepted by Sales for follow-up.",
  "Qualified prospects in active sales process.",
  "Deals that resulted in revenue.",
];

type PipelineFunnelSectionProps = {
  stages: FunnelStage[];
  conversionRate: number;
  metrics: Array<{ label: string; value: number }>;
  leads: Lead[];
  closedWon: number;
  totalLeads: number;
};

export function PipelineFunnelSection({
  stages,
  conversionRate,
  metrics,
  leads,
  closedWon,
  totalLeads,
}: PipelineFunnelSectionProps) {
  const [activeFilter, setActiveFilter] = useState<LeadFilterKey | null>(null);

  const filteredLeads = useMemo(() => {
    if (!activeFilter) return [];
    return sortLeadsForDisplay(filterLeads(leads, activeFilter));
  }, [activeFilter, leads]);

  function openStage(label: string) {
    const key = filterKeyFromFunnelLabel(label);
    if (key) setActiveFilter(key);
  }

  const activeLabel =
    activeFilter == null
      ? null
      : metrics.find((m) => filterKeyFromFunnelLabel(m.label) === activeFilter)
          ?.label ?? null;

  return (
    <>
      <div className="grid gap-6 lg:grid-cols-5">
        <div className="lg:col-span-3">
          <FunnelChart
            stages={stages}
            conversionRate={conversionRate}
            onStageClick={openStage}
            activeStageLabel={activeLabel}
          />
        </div>

        <Card className="lg:col-span-2">
          <h3 className="mb-4 text-sm font-semibold">Funnel Stages</h3>
          <div className="space-y-4">
            {metrics.map((m, i) => {
              const isActive = activeLabel === m.label;
              return (
                <button
                  key={m.label}
                  type="button"
                  onClick={() => openStage(m.label)}
                  className={cn(
                    "w-full rounded-lg border border-transparent pb-4 text-left transition last:pb-0",
                    "hover:border-border hover:bg-surface/80 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-uplight-blue",
                    isActive && "border-uplight-blue/30 bg-uplight-blue/5"
                  )}
                >
                  <div className="flex items-center justify-between gap-3 px-1 pt-1">
                    <span className="font-medium">{m.label}</span>
                    <span className="text-2xl font-bold tabular-nums">
                      {m.value}
                    </span>
                  </div>
                  <p className="mt-1 px-1 text-sm text-muted">
                    {STAGE_DESCRIPTIONS[i]}
                  </p>
                  {i > 0 && metrics[i - 1].value > 0 && (
                    <p className="mt-1 px-1 text-xs text-uplight-green">
                      {((m.value / metrics[i - 1].value) * 100).toFixed(1)}% from
                      previous stage
                    </p>
                  )}
                </button>
              );
            })}
          </div>

          <div className="mt-6 rounded-lg bg-uplight-navy/5 p-4">
            <p className="text-sm font-medium">Lead → Customer Conversion</p>
            <p className="mt-1 text-2xl font-bold text-uplight-navy">
              {conversionRate}%
            </p>
            <p className="mt-1 text-xs text-muted">
              {closedWon} ÷ {totalLeads} × 100
            </p>
          </div>
        </Card>
      </div>

      <LeadsFilterLightbox
        open={activeFilter !== null}
        filterKey={activeFilter}
        leads={filteredLeads}
        onClose={() => setActiveFilter(null)}
      />
    </>
  );
}
