import { FunnelChart } from "@/components/dashboard/funnel-chart";
import { Header } from "@/components/layout/header";
import { PageContent } from "@/components/layout/page-content";
import { Card } from "@/components/ui/card";
import { StatCard } from "@/components/ui/stat-card";
import { getFunnelStages, getPipelineMetrics } from "@/lib/data/dashboard-data";
import { fetchPipelineFromReport } from "@/lib/salesforce/reports";

const STAGE_DESCRIPTIONS = [
  "Leads generated by Marketing — webinars, LinkedIn, website forms, events.",
  "Leads showing enough engagement to qualify as interested.",
  "MQLs reviewed and accepted by Sales for follow-up.",
  "Qualified prospects in active sales process.",
  "Deals that resulted in revenue.",
];

export default async function PipelinePage() {
  const pipeline = await fetchPipelineFromReport();
  const funnelStages = getFunnelStages();

  const metrics = [
    { label: "Total Leads", value: pipeline.totalLeads, stage: funnelStages[0] },
    { label: "MQLs", value: pipeline.mqls, stage: funnelStages[1] },
    { label: "SQLs", value: pipeline.sqls, stage: funnelStages[2] },
    { label: "Opportunities", value: pipeline.opportunities, stage: funnelStages[3] },
    { label: "Closed Won", value: pipeline.closedWon, stage: funnelStages[4] },
  ];

  return (
    <>
      <Header
        title="Pipeline Visibility"
        description="Real-time view of where leads are in the sales funnel and how effectively they progress."
      />

      <PageContent className="space-y-6">
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
          {metrics.map((m) => (
            <StatCard key={m.label} label={m.label} value={m.value} accent="blue" />
          ))}
        </div>

        <div className="grid gap-6 lg:grid-cols-2">
          <FunnelChart
            stages={funnelStages}
            conversionRate={pipeline.conversionRate}
          />

          <Card>
            <h3 className="mb-4 text-sm font-semibold">Funnel Stages</h3>
            <div className="space-y-4">
              {metrics.map((m, i) => (
                <div key={m.label} className="border-b border-border pb-4 last:border-0">
                  <div className="flex items-center justify-between">
                    <span className="font-medium">{m.label}</span>
                    <span className="text-2xl font-bold tabular-nums">{m.value}</span>
                  </div>
                  <p className="mt-1 text-sm text-muted">{STAGE_DESCRIPTIONS[i]}</p>
                  {i > 0 && metrics[i - 1].value > 0 && (
                    <p className="mt-1 text-xs text-uplight-green">
                      {((m.value / metrics[i - 1].value) * 100).toFixed(1)}% from previous stage
                    </p>
                  )}
                </div>
              ))}
            </div>

            <div className="mt-6 rounded-lg bg-uplight-navy/5 p-4">
              <p className="text-sm font-medium">Lead → Customer Conversion</p>
              <p className="mt-1 text-2xl font-bold text-uplight-navy">
                {pipeline.conversionRate}%
              </p>
              <p className="mt-1 text-xs text-muted">
                {pipeline.closedWon} ÷ {pipeline.totalLeads} × 100
              </p>
            </div>
          </Card>
        </div>
      </PageContent>
    </>
  );
}
